[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/opt/oca/l10n-brazil,/opt/oca/field-service,/opt/oca/contract,/opt/oca/product-attribute,/opt/oca/bank-payment
data_dir = /var/lib/odoo
dbfilter = ^cisne$
list_db = False
proxy_mode = True
workers = 2
max_cron_threads = 1
limit_time_cpu = 120
limit_time_real = 240
limit_memory_soft = 2147483648
limit_memory_hard = 2684354560
log_level = info
